name: Test
on:
  pull_request:
  push: {branches: main}
  schedule: [{cron: '0 0 10 * *'}] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:
permissions: {contents: read}

jobs:
  test:
    uses: nodenv/.github/.github/workflows/test.yml@v4
    with: {superlinter: false} # TODO renable superlinter
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write

  # https://github.com/redhat-plumbers-in-action/differential-shellcheck
  shellcheck:
    permissions: {contents: read, security-events: write}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with: {fetch-depth: 0}
    - uses: redhat-plumbers-in-action/differential-shellcheck@929381c602ed76daa9b523e001ee29b82bd6d8e9 # v5.5.4
      with:
        severity: error # TODO strengthen
        token: ${{ secrets.GITHUB_TOKEN }}

  lts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - run: npm ci
    - run: npm run lint:lts

  checksums:
    runs-on: ubuntu-latest
    steps:
      # FIXME workaround https://github.com/actions/checkout/issues/910
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with: { fetch-depth: 0 }
    - run: npm ci
    - if: github.event_name == 'pull_request'
      run: npm run lint:checksums -- origin/${{github.base_ref}}
    - run: npm run lint:checksums -- HEAD^
      if: github.event_name == 'push'
